services:
  # White Board Online
  wbo:
    image: lovasoa/wbo
    container_name: wbo
    ports:
      - 5005:80
    volumes:
      - $DOCKER_PATH/wbo:/opt/app/server-data" 
    restart: unless-stopped

  # file browser - web-based file browser/manager
  filebrowser:
    container_name: filebrowser
    volumes:
      - $MEDIA_PATH:/srv
      - $DOCKER_PATH/filebrowser/filebrowser.db:/database.db
      - $DOCKER_PATH/filebrowser/.filebrowser.json:/.filebrowser.json
    environment:
      user: "$PUID:$PGID"
    ports:
      - 6543:80
    image: filebrowser/filebrowser

  # Joplin
  joplin:
    container_name: joplin
    image: joplin/server:latest
    depends_on:
        - joplindb
    ports:
        - "2230:2230"
    restart: unless-stopped
    environment:
        - APP_PORT=2230
        - APP_BASE_URL=http://joplin.$DOMAIN
        - DB_CLIENT=pg
        - POSTGRES_PASSWORD=joplinpsw
        - POSTGRES_DATABASE=joplin
        - POSTGRES_USER=joplinuser
        - POSTGRES_PORT=5432
        - POSTGRES_HOST=joplindb

  joplindb:
    container_name: joplindb
    image: postgres:13.1
    volumes:
        - $DOCKER_PATH/joplindb:/var/lib/postgresql/data
  #  ports:
   #     - "5435:5432"
    restart: unless-stopped
    environment:
        - POSTGRES_PASSWORD=joplinpsw
        - POSTGRES_USER=joplinuser
        - POSTGRES_DB=joplin

  # Mealie
  mealie:
    container_name: mealie
    image: hkotel/mealie:latest
    restart: unless-stopped
    ports:
      - 9925:80
    environment:
      TZ: $TZ
    volumes:
      - $DOCKER_PATH/mealie/data/:/app/data
    labels: 
      autoheal: true

  # Vaultwarden Password Manager
  vaultwarden:
    container_name: vaultwarden
    image: vaultwarden/server
    restart: always
    volumes:
      - $DOCKER_PATH/vaultwarden/data:/data
      - $DOCKER_PATH/vaultwarden/ssl:/ssl
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8089:8089
      - 3012:3012
    user: $PUID:$PGID
    environment:
      - LOG_FILE=/data/vaultwarden.log
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      #- SIGNUPS_ALLOWED=true
      - SIGNUPS_ALLOWED=false
      - INVITATIONS_ALLOWED=true
      - LOG_LEVEL=warn
      - EXTENDED_LOGGING=true
      - DOMAIN=https://bw.$DOMAINNAME
      - ROCKET_PORT=8089
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=$BW_TOKEN__SECRET
      - SMTP_HOST=$GM_SERVER
      - SMTP_FROM=$GM_USER__SECRET
      - SMTP_PORT=$GM_PORT
      - SMTP_SSL=true
      - SMTP_USERNAME=$GM_USER__SECRET
      - SMTP_PASSWORD=$GM_PSW__SECRET

  # Syncthing
  syncthing: 
    container_name: syncthing
    environment:
      - PUID=$PUID
      - PGID=$PGID
      - TZ=$TZ
      - UMASK_SET=022
    volumes:
      - $DOCKER_PATH/syncthing/config:/config
      - $DOCKER_PATH/syncthing/data1:/data1
      - $DOCKER_PATH/syncthing/data2:/data2
    ports:
      - 8384:8384
      - 22000:22000
      - 21027:21027/udp
    image: linuxserver/syncthing
    restart: unless-stopped

  # hasty paste
  hastypaste:
    container_name: hastypaste
    image: ghcr.io/enchant97/hasty-paste:1
    restart: unless-stopped
    environment:
      NEW_AT_INDEX: "true"
      DEFAULT_USE_LONG_ID: "false"
      ENABLE_PUBLIC_LIST: "true"
    volumes:
      - $DOCKER_PATH/hastypaste:/app/data
    ports:
      - 8069:8000

  # SearNGX
  searxng:
    container_name: searxng
    image: searxng/searxng:latest
    networks:
      - external
    ports:
     - "5080:8080"
    volumes:
      - $DOCKER_PATH/searxng:/etc/searxng:rw
    environment:
      - SEARXNG_BASE_URL=https://${SEARXNG_HOSTNAME:-localhost}/
    cap_drop:
      - ALL
    cap_add:
      - CHOWN
      - SETGID
      - SETUID
      - DAC_OVERRIDE
    logging:
      driver: "json-file"
      options:
        max-size: "1m"
        max-file: "1"